---
title: "5b"
author: "Arlante,Alpanghe,Subosa"
date: "2024-12-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

```
```{r}
graphiccard_url <- 'https://www.amazon.com/s?k=graphics+card&crid=6809YKENO5VZ&sprefix=graphics+%2Caps%2C516&ref=nb_sb_ss_ts-doa-p_1_9'

sus1 <- bow(graphiccard_url,
               user_agent = "Educational")
sus1
```

```{r}
library(rvest)

amazondf1 <- data.frame()

page1 <- scrape(sus1)

price1 <- page1 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description1 <- page1 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings1 <- page1 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews1 <- page1 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price1 <- price1[1:min(30, length(price1))]
description1 <- description1[1:min(30, length(description1))]
ratings1 <- ratings1[1:min(30, length(ratings1))]
reviews1 <- reviews1[1:min(30, length(reviews1))]

price1 <- c(price1, rep(NA, 30 - length(price1)))
description1 <- c(description1, rep(NA, 30 - length(description1)))
ratings1 <- c(ratings1, rep(NA, 30 - length(ratings1)))
reviews1 <- c(reviews1, rep(NA, 30 - length(reviews1)))


amazondf1 <- data.frame(
  Prices_amazon = price1,
  Descriptions_amazon = description1,
  Ratings_amazon = ratings1,
  Reviewss_amazon = reviews1,
  stringsAsFactors = FALSE
)

print(amazondf1)
```

```{r}
laptop_url <- 'https://www.amazon.com/s?k=laptop&crid=15FICF43OPKJ2&sprefix=laptop%2Caps%2C1359&ref=nb_sb_ss_ts-doa-p_1_6'

sus2 <- bow(laptop_url,
               user_agent = "Educational")
sus2
```

```{r}
library(rvest)

amazondf2 <- data.frame()

page2 <- scrape(sus2)

price2 <- page2 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description2 <- page2 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings2 <- page2 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews2 <- page2 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price2 <- price2[1:min(30, length(price2))]
description2 <- description2[1:min(30, length(description2))]
ratings2 <- ratings2[1:min(30, length(ratings2))]
reviews2 <- reviews2[1:min(30, length(reviews2))]

price2 <- c(price2, rep(NA, 30 - length(price2)))
description2 <- c(description2, rep(NA, 30 - length(description2)))
ratings2 <- c(ratings2, rep(NA, 30 - length(ratings2)))
reviews2 <- c(reviews2, rep(NA, 30 - length(reviews2)))


amazondf2 <- data.frame(
  Prices_amazon = price2,
  Descriptions_amazon = description2,
  Ratings_amazon = ratings2,
  Reviewss_amazon = reviews2,
  stringsAsFactors = FALSE
)

print(amazondf2)
```

```{r}
pccase_url <- 'https://www.amazon.com/s?k=pc+cases&crid=3232B9XX8J30L&sprefix=pccase%2Caps%2C674&ref=nb_sb_ss_ts-doa-p_3_6'

sus3 <- bow(pccase_url,
               user_agent = "Educational")
sus3
```

```{r}

library(rvest)

amazondf3 <- data.frame()

page3 <- scrape(sus3)

price3 <- page3 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description3 <- page3 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings3 <- page3 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews3 <- page3 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price3 <- price3[1:min(30, length(price3))]
description3 <- description3[1:min(30, length(description3))]
ratings3 <- ratings3[1:min(30, length(ratings3))]
reviews3 <- reviews3[1:min(30, length(reviews3))]

price3 <- c(price3, rep(NA, 30 - length(price3)))
description3 <- c(description3, rep(NA, 30 - length(description3)))
ratings3 <- c(ratings3, rep(NA, 30 - length(ratings3)))
reviews3 <- c(reviews3, rep(NA, 30 - length(reviews3)))


amazondf3 <- data.frame(
  Prices_amazon = price3,
  Descriptions_amazon = description3,
  Ratings_amazon = ratings3,
  Reviewss_amazon = reviews3,
  stringsAsFactors = FALSE
)

print(amazondf3)


```

```{r}

monitor_url <- 'https://www.amazon.com/s?k=monitors&crid=UGL8HSJMO1RM&qid=1732067471&refresh=1&sprefix=monitors%2Caps%2C588&ref=sr_pg_1'

sus4 <- bow(monitor_url,
               user_agent = "Educational")
sus4
```

```{r}
library(rvest)

amazondf4 <- data.frame()

page4 <- scrape(sus4)

price4 <- page4 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description4 <- page4 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings4 <- page4 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews4 <- page4 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price4 <- price4[1:min(30, length(price4))]
description4 <- description4[1:min(30, length(description4))]
ratings4 <- ratings4[1:min(30, length(ratings4))]
reviews4 <- reviews4[1:min(30, length(reviews4))]

price4 <- c(price4, rep(NA, 30 - length(price4)))
description4 <- c(description4, rep(NA, 30 - length(description4)))
ratings4 <- c(ratings4, rep(NA, 30 - length(ratings4)))
reviews4 <- c(reviews4, rep(NA, 30 - length(reviews4)))


amazondf4 <- data.frame(
  Prices_amazon = price4,
  Descriptions_amazon = description4,
  Ratings_amazon = ratings4,
  Reviewss_amazon = reviews4,
  stringsAsFactors = FALSE
)

print(amazondf4)

```

```{r}
cpu_url <- 'https://www.amazon.com/s?k=cpu&crid=3DBICI2YNNKHJ&sprefix=cpu%2Caps%2C768&ref=nb_sb_noss_1'

sus5 <- bow(cpu_url,
               user_agent = "Educational")
sus5
```

```{r}
library(rvest)

amazondf5 <- data.frame()

page5 <- scrape(sus5)

price5 <- page5 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description5 <- page5 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings5 <- page5 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews5 <- page5 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price5 <- price5[1:min(30, length(price5))]
description5 <- description5[1:min(30, length(description5))]
ratings5 <- ratings5[1:min(30, length(ratings5))]
reviews5 <- reviews5[1:min(30, length(reviews5))]

price5 <- c(price5, rep(NA, 30 - length(price5)))
description5 <- c(description5, rep(NA, 30 - length(description5)))
ratings5 <- c(ratings5, rep(NA, 30 - length(ratings5)))
reviews5 <- c(reviews5, rep(NA, 30 - length(reviews5)))


amazondf5 <- data.frame(
  Prices_amazon = price5,
  Descriptions_amazon = description5,
  Ratings_amazon = ratings5,
  Reviewss_amazon = reviews5,
  stringsAsFactors = FALSE
)

print(amazondf5)
```

```{r}
# 2. Out of the 30 products, pick 10 products and extract 20 reviews in each one which includes reviewer, date, individual rating, text review, title of review, and verified purchase.

library(rvest)
library(dplyr)

#1.
product_urls <- c('https://www.amazon.com/MSI-GeForce-RTX-3060-12G/dp/B08WPRMVWB/', 
'https://www.amazon.com/GIGABYTE-Graphics-WINDFORCE-GV-R76XTGAMING-OC-16GD/dp/B0CSVJZNNX/', 
'https://www.amazon.com/XFX-Speedster-Radeon-Graphics-RX-66XL8LFDQ/dp/B09HHLX543/',
'https://www.amazon.com/GIGABYTE-GeForce-WINDFORCE-Graphics-GV-N3050WF2OC-6GD/dp/B0D4XZXLL7/', 
'https://www.amazon.com/ASUS-ProArt-GeForce-Graphics-DisplayPort/dp/B0CSZCV12L/', 
'https://www.amazon.com/ASUS-SFF-Ready-GeForce-Graphics-DisplayPortTM/dp/B0D7KTZHXN/', 
'https://www.amazon.com/ASUS-ProArt-GeForce-Graphics-DisplayPort/dp/B0CCC7MP3H/', 
'https://www.amazon.com/ASUS-Graphics-DisplayPort-Axial-tech-Technology/dp/B0C7FNSHMQ/',
'https://www.amazon.com/SURALLOW-Graphics-2048SP-Computer-Ports%EF%BC%88Style/dp/B0CMD6L4CJ/','https://www.amazon.com/Graphics-1000MHz-DirectX-Computer-Accessories/dp/B0BN6PF3NR/'
)


scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```



```{r}
#2
product_urls <- c ('https://www.amazon.com/Amazon-Basics-Compatible-Adaptive-Response/dp/B0CP7TNX8C/', 
'https://www.amazon.com/Z-Edge-27-inch-Curved-Gaming-Monitor/dp/B08L3BHN3P/',
'https://www.amazon.com/Sceptre-DisplayPort-FreeSync-Frameless-E275W-FW100T/dp/B0CHHSFMRL/',
'https://www.amazon.com/PHILIPS-Adaptive-Replacement-Warranty-221V8LB/dp/B0CVM2GJCN/',
'https://www.amazon.com/Sceptre-Curved-Monitor-Speakers-C248W-1920RN/dp/B07KXSR99Y/',
'https://www.amazon.com/acer-Zero-Frame-Adaptive-Sync-FreeSync-Compatible/dp/B0D9MK23S7/',
'https://www.amazon.com/BONTEC-Monitor-Bracket-Screens-Adjustable/dp/B0D1TRFYDH/',
'https://www.amazon.com/SAMSUNG-ViewFinity-Ultra-WQHD-Borderless-LS34C502GANXZA/dp/B0C1KPXPM9/',
'https://www.amazon.com/Sceptre-E205W-16003R-Frameless-Speakers-Metallic/dp/B07743412C/',
'https://www.amazon.com/Sceptre-30-inch-Curved-Gaming-Monitor/dp/B07TXM7K4T/')

scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```



```{r}
#3
product_urls<- c("https://www.amazon.com/Intel-Celeron-N4020-14-Inch-Laptop/dp/B09YRY6QCX/", 
"https://www.amazon.com/HP-Micro-edge-Microsoft-14-dq0040nr-Snowflake/dp/B0947BJ67M/", "https://www.amazon.com/HP-Stream-BrightView-N4120-Graphics/dp/B0CZKPF2QH/", "https://www.amazon.com/KAIGERR-Computer-Quad-Core-Processor-Windows/dp/B0DP2D4J45/", "https://www.amazon.com/Dell-Inspiron-Touchscreen-i5-1155G7-Processor/dp/B0CTPCTW66/", "https://www.amazon.com/ASUS-Chromebook-Anti-Glare-1366x768-CM1402CM2A-DS44/dp/B0CJS1399P/", "https://www.amazon.com/MALLRACE-16-1-inch-Processor-Keyboard-Computer/dp/B0DMZT6H5D/", "https://www.amazon.com/HP-Portable-Student-Business-Quad-Core/dp/B0CPL25J3W/", "https://www.amazon.com/i5-13420H-Processor-GeForce-Display-ANV15-51-51H9/dp/B0CP8D4SM2/", "https://www.amazon.com/Naclud-Laptops-Computer-Quad-Core-Computers/dp/B0DK5NNMHG/")

```
```{r}
scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```


```{r}
#4
product_urls <- c("https://www.amazon.com/NZXT-CC-H61FW-01-Dual-Chamber-High-Performance-Management/dp/B0C89G9QDK/", "https://www.amazon.com/PCCOOLER-C3D310-Computer-Superior-Radiator/dp/B0CY2LDLZX/", "https://www.amazon.com/Corsair-4000D-Airflow-Tempered-Mid-Tower/dp/B08C7BGV3D/", "https://www.amazon.com/NZXT-Flow-Compact-Mid-Tower-Gaming/dp/B0B6Y15C5L/", "https://www.amazon.com/Airflow-Support-Mini-ITX-USB3-0x1-USB2-0x1I/dp/B0DFY9ZJGM/", "https://www.amazon.com/Cooler-Master-Transparent-Adjustable-Ventilated/dp/B0785GRMPG/", "https://www.amazon.com/DARKROCK-Supports-Graphics-Tempered-Pre-Installed/dp/B0D4QVMBTP/", "https://www.amazon.com/Okinos-Pre-Installed-Computer-Panoramic-Tempered/dp/B0CSYKJZJX/", "https://www.amazon.com/Antec-C5-ARGB-Simultaneously-Mid-Tower/dp/B0CWTPC32W/", "https://www.amazon.com/Sevenhero-EMBL-Radiator-Tempered-Panoramic/dp/B0CRZC28HR/")

scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```



```{r}
#5
product_urls <- c("https://www.amazon.com/SRESNAIL-Windows-Desktop-Computer-Ethernet/dp/B0DJ8Q8D3W/", "https://www.amazon.com/CyberGeek-J1-Quad-Core-3200MHz-Computer/dp/B0C6NP7Z8W/", "https://www.amazon.com/AMD-5700X-16-Thread-Unlocked-Processor/dp/B09VCHQHZ6/", "https://www.amazon.com/AMD-5500-12-Thread-Unlocked-Processor/dp/B09VCJ171S/", "https://www.amazon.com/AMD-Ryzen-5700X3D-16-Thread-Processor/dp/B0CQ4H4H7X/", "https://www.amazon.com/i7-14700K-Desktop-Processor-Integrated-Graphics/dp/B0CGJ41C9W/", 
"https://www.amazon.com/NUC12WSHi7-Computer-i7-1260P-Graphics-1TB/dp/B0BJDRK51K/", 
"https://www.amazon.com/AMD-Ryzen-5900X-24-Thread-Processor/dp/B08164VTWH/", "https://www.amazon.com/Intel-i9-12900KF-Desktop-Processor-Unlocked/dp/B09FWYK5M9/", 
"https://www.amazon.com/AMD-RyzenTM-9950X-32-Thread-Processor/dp/B0D6NNRBGP/")

scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}
all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```

